### ISSUE TITLE
Some changes on the API

### ISSUE THREAD

**Issue by isacikgoz** [waigani/diffparser#12]
Thanks for the useful library @waigani I am planning to use this project in my `git` application [gitin](https://github.com/isacikgoz/gitin)

I forked your repository and made some little changes:

- I exposed `diffHunk` to public
- I Added WholeRange along to newRange and OrigRange into the diffHunk

I needed diffhunks to create individual patches. It solved my problem, It does not have on impact to current usage of diffparser. If you don't mind, I would like to merge my commits into yours.

If it does not seem appropriate, it's OK for me. You can simply close the issue 👍

**Comment by nathanleiby** [comment]
Seems like a nice improvement. Opening a PR with your changes here: https://github.com/waigani/diffparser/pull/13

Thank you, and also looking forward to trying out some of your git tools.

**Comment by nathanleiby** [comment]
Merged #13

**Comment by isacikgoz** [comment]
Thank you @nathanleiby That was pretty fast!

I hope I didn't break things with those changes 👍
