### ISSUE TITLE
diffparser.Parse() can panic in diffparser.go:162 

### ISSUE THREAD

**Issue by metaleap** [waigani/diffparser#8]
I mean.. since `Parse` is designed to potentially return an `error`, might wanna attempt (even with bad inputs, I'm sure codelingo would agree :grin: ) *not* to `panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x5009da]`  ;)

For repro, here's the diff I tried to parse

    --- /home/me/c/go/src/github.com/metaleap/go-util-dev/dummy/dummy1.go	2017-04-12 07:55:00.033909298 +0200
    +++ /home/me/c/go/src/github.com/metaleap/go-util-dev/dummy/dummy1.go.23785.renamed	2017-04-12 09:07:32.238775316 +0200
    @@ -10,7 +10,7 @@
     //	temporary DUMMY AREA for testing various linters
     var testgolintUrl = "http://moohsssssssssssssss"
     
    -func ProcessInput(f *os.File, daFooBars map[*Foo]Foo) error {
    +func ProcessInput(f *os.File, daFooBars map[*Moo]Moo) error {
     	b, err := ioutil.ReadAll(f)
     	if err != nil {
     		return err
    @@ -25,11 +25,11 @@
     func foobar()                     { print(10) }
     func processBytes(b []byte) error { return nil }
     
    -type Foo struct {
    +type Moo struct {
     	num  int
     	chr  rune
     	str  string
    -	Foo  *Foo
    +	Foo  *Moo
     	numb int
     	t    bool
     	f    bool
    --- /home/me/c/go/src/github.com/metaleap/go-util-dev/dummy/dummy2.go	2017-04-12 08:15:05.406147538 +0200
    +++ /home/me/c/go/src/github.com/metaleap/go-util-dev/dummy/dummy2.go.23785.renamed	2017-04-12 09:07:32.241779726 +0200
    @@ -2,6 +2,6 @@
     
     import ()
     
    -func (_ *Foo) BarBaz(superfluous string, hint bool) {
    +func (_ *Moo) BarBaz(superfluous string, hint bool) {
     	Pretend("super", true)
     }
    --- /home/me/c/go/src/github.com/metaleap/go-util-dev/dummy.go	2017-04-12 07:34:09.567886286 +0200
    +++ /home/me/c/go/src/github.com/metaleap/go-util-dev/dummy.go.23785.renamed	2017-04-12 09:07:32.244784137 +0200
    @@ -4,4 +4,4 @@
     	"github.com/metaleap/go-util-dev/dummy"
     )
     
    -var Foo devdummy.Foo
    +var Foo devdummy.Moo

No final `\n` at the end provided though, that's the first thing I'm gonna try  =)

**Comment by metaleap** [comment]
OK by prepending-if-missing `"diff \n"` to the diff source passed to `Parse` we ensure `file` won't be `nil` and no `panic`. Leaving this here for the next guy, feel free to close unless you want to get fancy: one could consider for example adding the following minimalist heuristic (pseudocode) at the beginning:

    if (!diffsrc.hasPref("diff ") && diffsrc.Contains("@@") && diffsrc.Contains("--- ") && diffsrc.Contains("+++ ") then diffsrc = "diff \n" + diffsrc

Unusual use-case here too, the diff returned by `gorename -d` is just that .. "minimalist"

**Comment by metaleap** [comment]
Hm and it doesn't pick up the 3 files with their own old/new file paths either, instead everything is parsed as 1 file with empty strings for OrigName/NewName. Guess one has to hand-parse `gorename` outputs.. ah well, trivial enough format and I don't have to handle all cases, only gorename's

**Comment by metaleap** [comment]
So if anyone else wants to work with `gorename`'s diffs, this little beautifully formatted [beast](https://github.com/metaleap/zentient/blob/master/go/rename.go) will do the exact minimum needed 😁

**Comment by nathanleiby** [comment]
I believe this is fixed by https://github.com/waigani/diffparser/pull/9/ .. I've added an additional check to ensure that failed RegEx matching results in an error message.
